version: "0.1"

services:
  postgres:
    image: postgres
    env_file:
      - .env-dev
    hostname: db
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: