version: "0.1"

services:
  files:
    build: .
    env_file:
      - .env
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    hostname: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d files" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./logs:/var/log
    networks:
      - net


  nginx:
    build: ./nginx
    ports:
      - 6060:80
    depends_on:
      - celery-worker
    volumes:
      - ./static:/static
    networks:
      - net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - net
    depends_on:
      - files

  celery-worker:
    build: .
    container_name: celery-worker
    env_file:
      - .env
    restart: always
    command: python -m celery -A app worker -l info
    depends_on:
      - redis
    networks:
      - net

volumes:
  postgres_data:

networks:
  net: